// AUTO-GENERATED by tools/gen_bdt.py; do not edit manually.
#pragma once

#include <cstdint>

namespace carbon_sim {

constexpr std::uint32_t kBdtSignature = 0x54444243u;
constexpr std::uint16_t kBdtHeaderVersion = 1;
constexpr std::uint16_t kBdtHeaderSizeBytes = 16;
constexpr std::uint16_t kBdtEntrySizeBytes = 64;

constexpr std::uint16_t kDevClassCpu = 0x0001;
constexpr std::uint16_t kDevClassFpu = 0x0002;
constexpr std::uint16_t kDevClassUart = 0x0010;
constexpr std::uint16_t kDevClassSio = 0x0011;
constexpr std::uint16_t kDevClassPio = 0x0012;
constexpr std::uint16_t kDevClassTimer = 0x0013;
constexpr std::uint16_t kDevClassIrqCtrl = 0x0014;
constexpr std::uint16_t kDevClassDma = 0x0020;
constexpr std::uint16_t kDevClassBlockStorage = 0x0030;
constexpr std::uint16_t kDevClassCharStorage = 0x0031;
constexpr std::uint16_t kDevClassRtc = 0x0032;
constexpr std::uint16_t kDevClassGpio = 0x0033;
constexpr std::uint16_t kDevClassTrace = 0x0034;

constexpr std::uint32_t kCompatPolling = (1u << 0);
constexpr std::uint32_t kCompatIrq = (1u << 1);
constexpr std::uint32_t kCompatPortIo = (1u << 2);
constexpr std::uint32_t kCompatMmio = (1u << 3);
constexpr std::uint32_t kCompatWait = (1u << 4);

constexpr std::uint32_t kTurboQueue = (1u << 0);
constexpr std::uint32_t kTurboDma = (1u << 1);
constexpr std::uint32_t kTurboTimestamps = (1u << 2);
constexpr std::uint32_t kTurboPerf = (1u << 3);
constexpr std::uint32_t kTurboWatermarkIrq = (1u << 4);

constexpr std::uint32_t kFeatModeSwitchMask = (1u << 0);
constexpr std::uint32_t kFeatCsrNamespaceMask = (1u << 1);
constexpr std::uint32_t kFeatFabricMask = (1u << 2);
constexpr std::uint32_t kFeatCaiMask = (1u << 3);
constexpr std::uint32_t kFeatCpuidMask = (1u << 4);
constexpr std::uint32_t kFeatCapsMask = (1u << 5);
constexpr std::uint32_t kFeatAm9513Mask = (1u << 6);
constexpr std::uint32_t kFeatIommuHooksMask = (1u << 7);
constexpr std::uint32_t kFeatDeviceModelMask = (1u << 8);
constexpr std::uint32_t kFeatBdtMask = (1u << 9);
constexpr std::uint32_t kFeatTurboQueueMask = (1u << 10);
constexpr std::uint32_t kFeatPollingCompleteMask = (1u << 11);
constexpr std::uint32_t kFeatZ85UndocZ80Mask = (1u << 12);
constexpr std::uint32_t kFeatZ90Z180ClassMask = (1u << 13);
constexpr std::uint32_t kFeatZ38032bitExtendedMask = (1u << 14);
constexpr std::uint32_t kFeatZ480Native64Mask = (1u << 15);
constexpr std::uint32_t kFeatAm9512IeeeMask = (1u << 16);
constexpr std::uint32_t kFeatAm9513AsyncMask = (1u << 17);
constexpr std::uint32_t kFeatAm9514VectorMask = (1u << 18);
constexpr std::uint32_t kFeatAm9515TensorMask = (1u << 19);

constexpr unsigned kFeatWord0RxFifoLsb = 0;
constexpr unsigned kFeatWord0TxFifoLsb = 8;
constexpr unsigned kFeatWord0DmaChannelsLsb = 16;
constexpr unsigned kFeatWord0TimerCountLsb = 24;
constexpr unsigned kFeatWord1TimestampBitsLsb = 0;
constexpr unsigned kFeatWord1QueueCountLsb = 8;
constexpr unsigned kFeatWord1QueueDepthLsb = 16;

} // namespace carbon_sim
