#ifndef JC_CAPS_H
#define JC_CAPS_H

#include "jc_contracts.h"
#include "jc_contracts_autogen.h"

#define JC_CAP_HAS_V86_BIT JC_PERIPH_FEAT_HAS_V86_BIT
#define JC_CAP_HAS_V86_MASK JC_PERIPH_FEAT_HAS_V86_MASK
#define JC_CAP_HAS_ROMWBW_BIT JC_PERIPH_FEAT_HAS_ROMWBW_BIT
#define JC_CAP_HAS_ROMWBW_MASK JC_PERIPH_FEAT_HAS_ROMWBW_MASK
#define JC_CAP_HAS_LOCAL_VIDEO_BIT JC_PERIPH_FEAT_HAS_LOCAL_VIDEO_BIT
#define JC_CAP_HAS_LOCAL_VIDEO_MASK JC_PERIPH_FEAT_HAS_LOCAL_VIDEO_MASK
#define JC_CAP_HAS_PAGING_BIT JC_PERIPH_FEAT_HAS_PAGING_BIT
#define JC_CAP_HAS_PAGING_MASK JC_PERIPH_FEAT_HAS_PAGING_MASK
#define JC_CAP_HAS_IRQ_BIT JC_PERIPH_FEAT_HAS_IRQ_BIT
#define JC_CAP_HAS_IRQ_MASK JC_PERIPH_FEAT_HAS_IRQ_MASK

#define JC_CAP_HAS_V86 JC_CAP_HAS_V86_MASK
#define JC_CAP_HAS_ROMWBW JC_CAP_HAS_ROMWBW_MASK
#define JC_CAP_HAS_LOCAL_VIDEO JC_CAP_HAS_LOCAL_VIDEO_MASK
#define JC_CAP_HAS_PAGING JC_CAP_HAS_PAGING_MASK
#define JC_CAP_HAS_IRQ JC_CAP_HAS_IRQ_MASK

#define JC_CAP_PERIPH_WORD0 0u

#define JC_CAP_CHECK(capset, mask) \
  ((capset) && (((capset)->periph_features[JC_CAP_PERIPH_WORD0] & (mask)) != 0u))

#endif /* JC_CAPS_H */
